### ISSUE TITLE
Peer to peer code review! 16-Dec-2021

### ISSUE THREAD

**Issue by ivaan1992** [gemmen29/leaderboard#4]
Hi @gemmen29 😄 
Your project looks amazing, nice job!!! However, I found an issue that you should fix so your project could be so great. 
![Captura de pantalla de 2021-12-16 08-23-29](https://user-images.githubusercontent.com/73128809/146390139-e6118709-a673-482f-93e3-84eb4bfbc4a5.png)
When I click on the refresh button, I think the scores should be removed, but it doesn't work!! You should fix that part 🐛 . 

When you fix it, your project will be more complete!!! 😉 
Good luck and Happy coding!! 
✨

**Comment by gemmen29** [comment]
Thanks for feedback
